change_state_retired_film:
    path: '/{film}/stateretired'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ChangeStateToRetiredFilmController::changeStateToRetiredFilm'

create_film:
    path: '/create'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\CreateFilmController::createFilm'
    methods: [PUT]

show_films:
    path: '/showfilms'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ShowFilmsController::showFilms'

show_films_rooms:
    path: '/showfilmsrooms'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ShowFilmsWithRoomsController::showFilmsWithRooms'
