change_state_retired_film:
    path: '/{film}/stateretired'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ChangeStateToRetiredFilmController'
    methods: [PUT]

create_film:
    path: '/create'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\CreateFilmController'
    methods: [PUT]

show_film_by_id:
    path: '/show/{film}'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ShowFilmByIdController'
    methods: [PUT]

show_films:
    path: '/showfilms'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ShowFilmsController'
    methods: [PUT]

show_films_rooms:
    path: '/showfilmsrooms'
    controller: 'Javier\Cineja\Infrastructure\Controller\Film\ShowFilmsWithRoomsController'
    methods: [PUT]
